export {default as Layout} from './Layout'
export {default as Home} from './Home'
export {default as About} from './About'
export {default as Skills} from './Skills'
export {default as Work} from './Work'
export {default as Contact} from './Contact'
export {default as NotFound} from './NotFound'